version: '1.0'

services:
  gpu-borrow-website:
    image: gpu-borrow-website:latest
    build: .
    tty: true
    restart: always
    volumes:
      - ./instance:/app/instance
      - ./logs:/app/logs
    ports:
      - "9025:9025"
